version: 0.0
os: linux
files:
  - source: /
    destination: /csepf # and put them here in the server
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

    - location: scripts/setup_nginx.sh
     timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
